apiVersion: v2
name: system-app
description: A Helm chart for Kubernetes

type: application
version: 0.1.2        # chart version
appVersion: "1.16.0"  # application version

system-a: 
  replicaCount: 1
  image:
    repository: 419679277557.dkr.ecr.us-west-2.amazonaws.com/system
    pullPolicy: IfNotPresent
    tag: "latest"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
  
  autoscaling:
    enabled: false

  serviceAccount:
    create: true
